baseurl = "https://www.nicolacantalupo.it/"
languageCode = "it"
languageLang = "it"
title = "tecnico informatico webmaster assistenza riparazione computer sapri"
enableRobotsTXT = "true"
theme = "sodium"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5